class_level: fundamentals
link_to_survey: testing
link_to_slides: testing
students:
  - name: Finn Mertens
    email: matt+finn@masterpoint.io

  - name: Jake Dogg
    email: matt+jake@masterpoint.io
